# Generated by Django 5.2.1 on 2025-05-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_rename_expenses_expense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'managed': False},
        ),
    ]
