# Generated by Django 5.2.1 on 2025-05-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_alter_expense_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expense',
            table='expense_expenses',
        ),
    ]
